[project]
name = "test-task"
version = "0.1.0"
description = ""
authors = [
    {name = "Andrei-KV",email = "a.v.kovalev9@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0.0"
dependencies = [
    "sqlalchemy (>=2.0.44,<3.0.0)",
    "langchain-text-splitters (>=1.0.0,<2.0.0)",
    "pytelegrambotapi (>=4.29.1,<5.0.0)",
    "python-dotenv (>=1.2.1,<2.0.0)",
    "schedule (>=1.2.2,<2.0.0)",
    "markdown (>=3.9,<4.0)",
    "pypandoc (>=1.15,<2.0)",
    "beautifulsoup4 (>=4.14.2,<5.0.0)",
    "pandoc (>=2.4,<3.0)",
    "psycopg2-binary (>=2.9.11,<3.0.0)",
    "aioredis (>=2.0.1,<3.0.0)",
    "asyncpg (>=0.29.0,<1.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
